services:
    naviapps_user.change_password.form.flow:
        class: '%naviapps_user.change_password.form.flow%'
        parent: craue.form.flow
        arguments: ['%fos_user.change_password.form.type%']
