services:
    naviapps_user.change_password.form.flow:
        class: Naviapps\Bundle\UserBundle\Form\Flow\ChangePasswordFormFlow
        parent: craue.form.flow
        arguments: ['%fos_user.change_password.form.type%']
