services:
    naviapps_user.deactivation.form.type:
        class: Naviapps\Bundle\UserBundle\Form\Type\DeactivationFormType
        tags:
            - { name: form.type }
        arguments: ['%fos_user.model.user.class%']

    naviapps_user.deactivation.form.flow:
        class: '%naviapps_user.deactivation.form.flow%'
        parent: craue.form.flow
        arguments: ['%naviapps_user.deactivation.form.type%']
