services:
    naviapps_user.resetting.form.flow:
        class: Naviapps\Bundle\UserBundle\Form\Flow\ResettingFormFlow
        parent: craue.form.flow
        arguments: ['%fos_user.resetting.form.type%']
